### ISSUE TITLE
seems like a version conflict is giving a bug

### ISSUE THREAD

**Issue by WillEhrendreich** [SilkyFowl/Avalonia.FuncUI.LiveView#21]
Hey, I was trying to get this to work, and it seems like it doesn't like a change that's happened in avalonia funcui version 1
```

Unhandled exception. System.TypeLoadException: Could not load type 'Avalonia.FuncUI.Builder.ViewBuilder' from assembly 'Avalonia.FuncUI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Avalonia.FuncUI.LiveView.StateStoreModule.init()
   at Avalonia.FuncUI.LiveView.LiveViewWindow..ctor()
```

how would you recommend working around this?

**Comment by SilkyFowl** [comment]
LiveView v0.1.1.1 has been released for Avalonia.FuncUI v1.0.1. Please check it.

**Comment by WillEhrendreich** [comment]
keeps having an exception of a type initializer, and says system drawing common not supported?

**Comment by SilkyFowl** [comment]
Thanks for the feedback.
I am sorry, but I have not yet been able to reproduce issue with LiveView v0.1.1.1.
Do you have any steps or hints on how to reproduce the issue?

I have a minimal repository using v0.1.1.1 that I use for isuue verification.
[SilkyFowl/SilkyFowl.Avalonia.FuncUI.LiveView.Demo.0.0.1.1](https://github.com/SilkyFowl/SilkyFowl.Avalonia.FuncUI.LiveView.Demo.0.0.1.1)
I hope you will find this helpful until I have updated the README.

**Comment by SilkyFowl** [comment]
@WillEhrendreich The README has been updated. I hope this will be helpful.

**Comment by WillEhrendreich** [comment]
Can you do a non paket version? I can't get paket to run. Baffling, but true.

**Comment by SilkyFowl** [comment]
@WillEhrendreich Yes, it is possible to use it without using Paket. Instructions can be found [here in the README](https://github.com/SilkyFowl/Avalonia.FuncUI.LiveView#without-paket). Will this procedure work?

**Comment by SilkyFowl** [comment]
@WillEhrendreich  Updated to version 0.0.3.
In addition, I created a demo repository without Paket.

- [SilkyFowl.Avalonia.FuncUI.LiveView.Demo](https://github.com/SilkyFowl/SilkyFowl.Avalonia.FuncUI.LiveView.Demo) 
- [SilkyFowl.Avalonia.FuncUI.LiveView.Demo.Paket](https://github.com/SilkyFowl/SilkyFowl.Avalonia.FuncUI.LiveView.Demo.Paket) 

Please check it out if you like.

**Comment by WillEhrendreich** [comment]
@SilkyFowl you the real mvp. thank you, I'll check it out as soon as I can! :)
