### ISSUE TITLE
eval button causes an exception, 

### ISSUE THREAD

**Issue by WillEhrendreich** [SilkyFowl/Avalonia.FuncUI.LiveView#31]
Exception has occurred: CLR/System.TypeInitializationException
An unhandled exception of type 'System.TypeInitializationException' occurred in Avalonia.FuncUI.LiveView.dll: 'The type initializer for '<StartupCode$Avalonia-FuncUI-LiveView>.$LiveView' threw an exception.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.Exception : Error creating evaluation session: StopProcessingExn
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1448.Invoke(String message)
   at FSharp.Compiler.Interactive.Shell.FsiEvaluationSession..ctor(FsiEvaluationSessionHostConfig fsi, String[] argv, TextReader inReader, TextWriter outWriter, TextWriter errorWriter, Boolean fsiCollectible, FSharpOption`1 legacyReferenceResolver)
   at FSharp.Compiler.Interactive.Shell.FsiEvaluationSession.Create(FsiEvaluationSessionHostConfig fsiConfig, String[] argv, TextReader inReader, TextWriter outWriter, TextWriter errorWriter, FSharpOption`1 collectible, FSharpOption`1 legacyReferenceResolver)
   at Avalonia.FuncUI.LiveView.FsiSession.create()
   at <StartupCode$Avalonia-FuncUI-LiveView>.$LiveView..cctor()

**Comment by WillEhrendreich** [comment]
no idea why, but i don't get this anymore.. closing
